Add files via upload
DimitriiKorol/JS_Advanced-GB pull request #12
Opened 2020-10-05 12:59 UTC by DimitriiKorol

Сделал одно задание - удаление. Не пойму работает или нет, не понял как проверять работу скрипта именно на стороне сервера.

2020-10-05 15:20 UTC, Om1X requested changes

2020-10-05 15:20 UTC, Om1X commented on public/js/CartComp.js
> +        remove(item) {
запрос делаем к нашему api

2020-10-05 15:20 UTC, Om1X commented on public/js/CartComp.js
> +                        }
тут принимаем решение, удаляем или меняем колчество, соответственно делаем запрос через deletJson или putJson.

2020-10-05 15:20 UTC, Om1X commented on server/cart.js
> +  if (find.quantity === 1) {
У нас метод удаления, поэтому проверять количество не имеет смысла, просто удаляем товар.

2020-10-06 17:55 UTC, DimitriiKorol commented
Исправлено

2020-10-06 17:55 UTC, merged