Add files via upload
DimitriiKorol/JS_Advanced-GB pull request #6
Opened 2020-09-28 12:55 UTC by DimitriiKorol

Сделал частично, но getRequest из методички у меня то ли поломался, то ли еще чего, не отображаются товары и все тут. Пока что пытаюсь разобраться, поэтому 1-е, 2-е, что не связано с этим или связано частично - сделал, 3-е пока что нет. Как разберусь, что сломалось, перезалью, напишу.

2020-09-28 16:50 UTC, Om1X requested changes

2020-09-28 16:50 UTC, Om1X commented on script.js
> +        },
не нужен он нам, это была функция для задания на третьем уроке и все. Забудьте про нее. У нас уже был метод с fetch, его и используем.

2020-09-28 16:50 UTC, Om1X commented on script.js
> +                }
забываем про `document.querySelector(). У нас есть шаблоны и данные. Оперируем ими, а прямые воздействия, как в "ванилке" остаются в прошлом (кроме уж совсем уникальных кейсов, где без этого никак).

2020-09-28 16:50 UTC, Om1X commented on script.js
> +            }
аналогично замечанию выше. Все это можно заменить директивой v-show в шаблоне и одним полем isVisibleCart: false, и менять его значение при клике.

2020-10-02 17:19 UTC, closed without merging

2020-10-02 17:20 UTC, DimitriiKorol commented
Сделаю отдельную ветку для проекта на Vue